baseURL = 'https://verifythis.github.io/'
languageCode = 'en-us'
title = 'VerifyThis'

pygmentsStyle = "monokai"
pygmentsUseClasses = true
pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true




[markup]
  defaultMarkdownHandler = 'goldmark'
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = true
        title = true
        image = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[[menu.main]]
    name = "VerifyThic LTC"
    url = "/ltc/"
    weight = 2


[[menu.ltc]]
    name = "Next Event"
    url = "/ltc/events/2024-01-23-online-event/"
    weight = 1

[[menu.ltc]]
    name = "Current Challenge"
    url = "/ltc/03memcached"
    weight = 2

[[menu.ltc]]
    identifier = "prev"
    name = "Previously"
    weight = 3

[[menu.ltc]]
    parent = "prev"
    name = "1st Challenge: Hagrid"
    url = "/ltc/01hagrid"
    weight = 1

[[menu.ltc]]
    parent = "prev"
    name = "Challenge: Casino"
    url = "/ltc/02casino"
    weight = 2

[[menu.ltc]]
    parent = "prev"
    name = "Events"
    url = "/ltc/events"
    weight = 3
